# Build the ğŸ Python package ğŸ“¦ for distribution
# For more information see:
# https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

name: Build distribution ğŸğŸ“¦

on:
  workflow_run:
    workflows: [Test installation]
    types:
      - completed
    branches:
      - "**"

jobs:
  build-package:

    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == "success" }}

    steps:
      - uses: actions/checkout@v4

      - run: |
          echo "${{ github.env }}"

      - name: Set up ğŸ 3.x
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install ğŸ”¨
        run: |
          python -m pip install build --user

      - name: Build ğŸğŸ“¦
        run: |
          python -m build

      - name: ğŸ—ƒï¸ build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package-dist
          path: dist/
