# Workflow that triggers when commits are pushed 

name: Branch workflow

on:
  push:
    branches-ignore: ["main"]
    

jobs:
  test-install-python-version:
    name: Test install on ğŸ
    uses: ./test-install.yml
    with:
      versions: '["3.10", "3.11", "3.12"]'
      lint: true
      pytest: true

  build-package:
    name: Build distribution ğŸ“¦
    uses: ./build-package.yml
    with:
      artifact-name: "package-dist"
