# Workflow that triggers when commits are pushed 

name: Branch workflow

on:
  pull_request:
    types: [synchronize]
    branches: ["main"]
    paths-ignore: ["**/__about__.py"]
  push:
    branches-ignore: ["main"]
    paths-ignore: ["**/__about__.py"]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-install-python-version:
    name: Test install on üêç
    uses: ./.github/workflows/test-install.yml
    with:
      versions: '["3.10", "3.11", "3.12"]'
      lint: true
      pytest: true
      artifact-name: "pytest-results"

  build-package:
    name: Build distribution üì¶
    needs: test-install-python-version
    uses: ./.github/workflows/build-package.yml
    with:
      artifact-name: "package-dist"

  publish-to-pypi:
    name: Publish üêçüì¶ to PyPI
    if: ${{ !github.event.pull_request.merged }}
    steps:
      - name: Log context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  version-bump-dev:
    name: Version bump ‚ÜóÔ∏è (pre-release)
    if: ${{ !github.event.pull_request.merged }}
    steps:
      - name: Log context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
