# This worflow publishes the ğŸ Python package ğŸ“¦ distribution to PyPI
# For more information see:
# https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

name: Publish ğŸğŸ“¦ to PyPI

on:
  workflow_call:
    inputs:
      artifact-name:
        description: "Artifact name of the distribution package"
        type: string
        default: "package-dist"
        required: false
      test:
        description: "Test publish to TestPyPI instead"
        type: boolean
        default: false
        required: false

jobs:
  publish-to-pypi:

    runs-on: ubuntu-latest
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    environment:
      name: ${{ inputs.test && 'testpypi' || 'pypi' }}
      url: ${{ inputs.test && format('{0}/{1}', 'https://test.pypi.org/p', github.repository.name) || format('{0}/{1}', 'https://pypi.org/p', github.repository.name) }}

    steps:
      - name: Download ğŸ—ƒï¸
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: dist/

      - name: Publish ğŸğŸ“¦ to ${{ inputs.test && 'TestPyPI' || 'PyPI' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: ${{ inputs.test && 'https://test.pypi.org/legacy/' || 'https://upload.pypi.org/legacy/' }}
      
